### ISSUE TITLE
Qualcosa che non quadra in file2

### ISSUE THREAD

**Issue by gabolander** [riminilug/demoproject#1]
In file2.txt non si capisce un oscia!! ;-)

**Comment by gabolander** [comment]
Commento di prova alla _issue_ aperta..
Al **file2.txt** non si capisce nulla, semplicemente perché l'ho scritto **io** !!!

**Comment by itarozzi** [comment]
Prova con il traduttore di google :+1: 

(.....giusto per provare a rispondere)

**Comment by battarsa** [comment]
In data mercoled� 4 marzo 2015 04:10:38, Ivan Tarozzi ha scritto:

> Prova con il traduttore di google :+1:
> 
> (.....giusto per provare a rispondere)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/riminilug/demoproject/issues/1#issuecomment-77147173

prova, commento inviato via mail

## 

Samuele Battarra
battarsa@email.it

**Comment by gabolander** [comment]
Ma LooL !!!! ;DD

**Comment by gabolander** [comment]
Ok, ho provato ad utilizzare google translate, come suggerito da Ivan ( :D ), ed ora l'ho capito.
Per quel che mi riguarda, questa issue si può chiudere.
Come si fa a chiudere? Lock issue?

**Comment by riminilug-lab** [comment]
OK!  :)   No, per chiuderla c'è il tastino  a fondo pagina : Close Issue!

**Comment by gabolander** [comment]
Ohi Ohi!!! .. sfuggito proprio [?]

Sent with MailTrack
https://mailtrack.io/install?source=signature&lang=en&referral=gabriele.zappi@gmail.com&idSignature=22

2015-03-04 17:02 GMT+01:00 riminilug notifications@github.com:

> OK! :) No, per chiuderla c'è il tastino verde a fondo pagina!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/riminilug/demoproject/issues/1#issuecomment-77185577.

## 

Best regards,

_Gabriele Zappi_
_http://www.gabrielezappi.net http://www.gabrielezappi.net_
GNU/Linux user #380098
